### PR TITLE
When implicitly forking a page, include the page.

### PR DESCRIPTION
**Pull request by nrn**

### CODE REVIEW

**Comment by paul90** [comment]
Have both explicit and implicit fork use `forkPage` to hold the page being forked. Will hopefully aid comprehension when we look at this, and the associated server code in some years time.

**Comment by WardCunningham** [comment]
This change in the client to server message format is an improvement that depends on us deploying client and server together. Merge at will to be installed as a new wiki, not client or server individually.

**Comment by paul90** [comment]
As discussed on call, adding the date to the implicit fork event - this value stays on the client, but ensures that it is preserved if the fork is repeated without reloading the page.

**Comment by paul90** [comment]
Published as + wiki-client@0.28.0

**Pull request merged**
