### PR TITLE
Restore browser test page

### PR DESCRIPTION
**Pull request by paul90**
For some reason this was over looked when the siteAdapter was created. Here we add mocking of the siteAdapter calls, so that the existing tests run.

### CODE REVIEW

**Comment by WardCunningham** [comment]
I am having a little trouble understanding the overall approach here. My presumption would be that a mock would omit network calls for the sake of testing non-network logic. But I see ajax requests in the mock itself? Are these the ajax calls required to get the exist tests to run?

**Comment by paul90** [comment]
Just reusing the server mock that already exists, so provides an easy solution. Would be better to have two versions of the mocked siteAdapter gets, for page found and not found.

**Comment by WardCunningham** [comment]
I'm happy to see this working again. Now I need to build it into my workflow. Better tests are alway an option but fixing this oversight shouldn't wait for that.

**Comment by paul90** [comment]
Published as + wiki-client@0.16.0

**Pull request merged**
