### PR TITLE
skip item being edited in renderFrom()

### PR DESCRIPTION
**Pull request by paul90**
Looks to be a fix for #266.

### CODE REVIEW

**Comment by ig3** [comment]
This does fix #266 for me.

**Comment by paul90** [comment]
As far as I can see it will. Just waiting for it to be double checked

**Comment by WardCunningham** [comment]
I'm pleased to have the chance to apply the neat feature of github where it ignores whitespace changes and shows this to be the single line change that it is.

https://github.com/fedwiki/wiki-client/pull/267/commits/8d8dbd83570115a77c583082b2a1b5db742f7ec4?diff=unified&w=1

This seems safe in that it handles a case that I doubt what considered when this rendering loop was coded. I'm happy to see this merged knowing that any future developer would need to "blame" the history to find the unexpected consequences of following the now excluded statements.

Let's give @joshuabenuck a day or two to look at this because he is more aware of the many cases in which a page is rendered. We overlap some activity with the server turnaround that writes an action and that means we are expecting (maybe depending upon) relative quiescence while this happens.

**Comment by joshuabenuck** [comment]
My first thought of a fix was to put a guard around plugin.do in [editor.coffee](https://github.com/fedwiki/wiki-client/blob/master/lib/editor.coffee#L103), but it isn't immediately obvious what such a guard would look like.

The approach used here is good. I think it is simpler than the one I was considering above. Once the edit is finished, the item that was skipped will be rerendered when the focusout handler is called so there shouldn't be any downsides.

**Comment by paul90** [comment]
Thanks for looking at that @joshuabenuck.

**Comment by paul90** [comment]
Published as + wiki-client@0.20.3

**Pull request merged**
