### PR TITLE
Shift for hover effects on items and actions.

### PR DESCRIPTION
**Pull request by WardCunningham**
This pull request improves the item/action hover logic several ways.

* The hover highlight and scroll effects require that the shift key be pressed.
* Shift will highlight immediately when already hovering.
* Highlight state (class .target) is set and cleared rather than toggled avoiding sync problems.
* Hover over events highlights and scrolls other pages.

The scroll positioning would be better if it aligned like items on item hover. This has many boundary conditions that I will explore and then submit in a later pull request.

### CODE REVIEW

**Comment by WardCunningham** [comment]
I've done a preview install of these commits on fed.wiki.org. I've been using that code to explore some of the conversation-club views from december's happening. [lineup](http://fed.wiki.org/journal.hapgood.net/view-between-rooms/kate.au.fedwikihappening.net/view-between-rooms/frances.uk.fedwikihappening.net/view-between-rooms/forage.ward.fed.wiki.org/view-between-rooms)

**Comment by WardCunningham** [comment]
This pull request is now complete and ready to be merged.

**Comment by WardCunningham** [comment]
Ok, I drew a picture. Now this is ready to merge.

image

**Comment by paul90** [comment]
Published as **+ wiki-client@0.4.6**

**Pull request merged**
