### PR TITLE
Add a paper scrollable div inside the pages viewport

### PR DESCRIPTION
**Pull request by sillydeveloper**
- This adds a new div called "paper" that contains the scrollable viewport instead of the page.
- Adds a "asTitle" utility method to convert a slug back into a title.

@WardCunningham will check this out for a bit with the various plugins to ensure it doesn't break anything.

### CODE REVIEW

**Comment by WardCunningham** [comment]
Edits to `static.html` and `editor.coffee` must have slipped in from other editing.

**Comment by sillydeveloper** [comment]
Finally pushed up the requested changes!

**Comment by WardCunningham** [comment]
We produce client.js and client.max.js but use only client.js in production installs.

I'm not seeing a second commit. Did you push code to this branch this morning?

**Comment by paul90** [comment]
Yes `client.max.js` is correct - this is then passed through uglify to give the final client. 

May seem wrong as many would use `client.js` and `client.min.js`, but at the time this was put in place the map file linked back to the coffeescript source. *I wonder when that got broken...*

**Comment by paul90** [comment]
Really not sure what this pull request is trying to achieve?

> This adds a new div called "paper" that contains the scrollable viewport instead of the page.

I don't see, or recall, any reason why this extra level of nesting is necessary!

> Adds a "asTitle" utility method to convert a slug back into a title.

What is this for? Conversion of a title into a slug is a one way action - created using `name.replace(/\s/g, '-').replace(/[^A-Za-z0-9-]/g, '').toLowerCase()`

As far as I can see this method is not achieving anything. The correct title is getting used rather than that created by this `asTitle` method. For example, a page with the title `a - b` is getting correctly displayed despite getting converted to a slug of `a---b` and then a title of `a   b` by this method.

**Comment by WardCunningham** [comment]
This separates the two kinds of page halo we use. One kind rests around the page showing that it is active (think arrow keys), the other rests within the page showing its type (think blue, green and yellow). The extra layer of div allows both to be present at the same time. Another subtle feature is that the type halo scrolls with the "paper" so that one never read text through the halo.

The title manipulation was to "guess" at a more likely title when the page is being fetched. This lingers when operating on a slow internet. I suggested we go so far as to guess that the page first paragraph will be that which we find in a sitemap. This would be replaced with the full page and proper title once it arrives.

I had pointed Andrew in these directions while I wrote and he proof-read my introduction to hacking wiki.
http://dev.asia.wiki.org/view/hacking-federated-wiki/view/render-pages

Much of this slips from my memory so careful review is appropriate.

**Comment by paul90** [comment]
That rings a bell, it had completely slipped from my mind.

**Comment by paul90** [comment]
Thank you Andrew, @sillydeveloper

**Pull request merged**
