### PR TITLE
Correct jQuery UI built

### PR DESCRIPTION
**Pull request by paul90**
This is a fix for fedwiki/wiki-plugin-reduce#7

### CODE REVIEW

**Comment by WardCunningham** [comment]
Is this simply a version synchronization issue between jQuery and jQuery UI?

**Comment by paul90** [comment]
No, there are two downloads - the quick download (that that I assumed included everything, but doesn't), and the custom download.

**Comment by WardCunningham** [comment]
Ah. Thanks.

**Comment by paul90** [comment]
Published as + wiki-client@0.5.1

**Pull request merged**
