### PR TITLE
display flex for native scrolling

### PR DESCRIPTION
**Pull request by WardCunningham**
@baldurbjarnason has guided me through this modest improvement styling the lineup using flex for native scrolling. This is expected to work better on mobile. (Test this before merging.)

Note: this and related work is more about investing in the longevity of our codebase than adding mobile as a feature. I once referred to this as "chronological scaling" before we had a clear notion of what that would require. [post](http://code.fed.wiki/chronological-scaling.html)

### CODE REVIEW

**Comment by paul90** [comment]
Only thing I've spotted so far is that the horizontal scrollbar on the lineup needs hiding, and page being opened no longer is scrolled into view.

**Comment by WardCunningham** [comment]
@paul90 recommended this simple fix, [bfa2e8b](https://github.com/fedwiki/wiki-client/pull/327/commits/bfa2e8b5f985e4b74e3aefde94bb643ba7879ac8), and adds "if we were not moving away from browserify it could be fixed by adding [browserify-optional](https://github.com/devongovett/browserify-optional) into the mix."

**Comment by paul90** [comment]
Cherry picking the change here to the new decaffeinated main branch added a bunch of commits from the migration. Restored by force-push, this PR will be closed and reopened on the new main branch.

**Comment by paul90** [comment]
Closed in favour of #328, based on the JavaScript main branch.

**Pull request closed without merging**
